server:
  port: 7070

spring:
  application:
    name: eurka-server

eureka:
  client:
    #        默认注册中心也是一个client，以下两句表明了这是一个注册中心
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/